# Spaceship Prompt Configuration
# This file is sourced by Spaceship

# Display settings
SPACESHIP_PROMPT_ADD_NEWLINE=true
SPACESHIP_PROMPT_SEPARATE_LINE=true
SPACESHIP_PROMPT_PREFIXES_SHOW=true
SPACESHIP_PROMPT_SUFFIXES_SHOW=true
SPACESHIP_PROMPT_DEFAULT_PREFIX="via "
SPACESHIP_PROMPT_DEFAULT_SUFFIX=" "

# Character
SPACESHIP_CHAR_SYMBOL="❯"
SPACESHIP_CHAR_SYMBOL_ROOT="❯"
SPACESHIP_CHAR_SYMBOL_SECONDARY="❯"
SPACESHIP_CHAR_SUFFIX=" "
SPACESHIP_CHAR_COLOR_SUCCESS="green"
SPACESHIP_CHAR_COLOR_FAILURE="red"
SPACESHIP_CHAR_COLOR_SECONDARY="yellow"

# Time
SPACESHIP_TIME_SHOW=false
SPACESHIP_TIME_PREFIX="at "
SPACESHIP_TIME_SUFFIX=" "
SPACESHIP_TIME_FORMAT="%D{%H:%M:%S}"
SPACESHIP_TIME_12HR=false
SPACESHIP_TIME_COLOR="yellow"

# Username
SPACESHIP_USER_SHOW=true
SPACESHIP_USER_PREFIX="with "
SPACESHIP_USER_SUFFIX=" "
SPACESHIP_USER_COLOR="yellow"
SPACESHIP_USER_COLOR_ROOT="red"

# Hostname
SPACESHIP_HOST_SHOW=false
SPACESHIP_HOST_SHOW_FULL=false
SPACESHIP_HOST_PREFIX="at "
SPACESHIP_HOST_SUFFIX=" "
SPACESHIP_HOST_COLOR="blue"
SPACESHIP_HOST_COLOR_SSH="green"

# Directory
SPACESHIP_DIR_SHOW=true
SPACESHIP_DIR_PREFIX=""
SPACESHIP_DIR_SUFFIX=" "
SPACESHIP_DIR_TRUNC=3
SPACESHIP_DIR_TRUNC_REPO=true
SPACESHIP_DIR_COLOR="cyan"
SPACESHIP_DIR_LOCK_SYMBOL=" "
SPACESHIP_DIR_LOCK_COLOR="red"

# Git
SPACESHIP_GIT_SHOW=true
SPACESHIP_GIT_PREFIX="["
SPACESHIP_GIT_SUFFIX=""
SPACESHIP_GIT_SYMBOL=" "

# Git branch
SPACESHIP_GIT_BRANCH_SHOW=true
SPACESHIP_GIT_BRANCH_PREFIX=""
SPACESHIP_GIT_BRANCH_SUFFIX="]"
SPACESHIP_GIT_BRANCH_COLOR="magenta"

# Git status
SPACESHIP_GIT_STATUS_SHOW=true
SPACESHIP_GIT_STATUS_PREFIX="["
SPACESHIP_GIT_STATUS_SUFFIX="]"
SPACESHIP_GIT_STATUS_COLOR="red"
SPACESHIP_GIT_STATUS_UNTRACKED="?"
SPACESHIP_GIT_STATUS_ADDED="+"
SPACESHIP_GIT_STATUS_MODIFIED="!"
SPACESHIP_GIT_STATUS_RENAMED="»"
SPACESHIP_GIT_STATUS_DELETED="✘"
SPACESHIP_GIT_STATUS_STASHED="$"
SPACESHIP_GIT_STATUS_UNMERGED="="
SPACESHIP_GIT_STATUS_AHEAD="⇡"
SPACESHIP_GIT_STATUS_BEHIND="⇣"
SPACESHIP_GIT_STATUS_DIVERGED="⇕"

# Node.js
SPACESHIP_NODE_SHOW=false
SPACESHIP_NODE_PREFIX="["
SPACESHIP_NODE_SUFFIX="]"
SPACESHIP_NODE_SYMBOL="⬢ "
SPACESHIP_NODE_COLOR="green"

# Bun
SPACESHIP_BUN_SHOW=true
SPACESHIP_BUN_PREFIX="["
SPACESHIP_BUN_SUFFIX="]"
SPACESHIP_BUN_SYMBOL="🥟 "
SPACESHIP_BUN_COLOR="yellow"

# Ruby
SPACESHIP_RUBY_SHOW=true
SPACESHIP_RUBY_ASYNC=false
SPACESHIP_RUBY_PREFIX="["
SPACESHIP_RUBY_SUFFIX="]"
SPACESHIP_RUBY_SYMBOL="💎 "
SPACESHIP_RUBY_COLOR="red"

# AWS (requires AWS_PROFILE or AWS_VAULT env var to be set)
SPACESHIP_AWS_SHOW=true
SPACESHIP_AWS_PREFIX="["
SPACESHIP_AWS_SUFFIX="]"
SPACESHIP_AWS_SYMBOL="☁️  "
SPACESHIP_AWS_COLOR="yellow"

# Python
SPACESHIP_PYTHON_SHOW=true
SPACESHIP_PYTHON_PREFIX="["
SPACESHIP_PYTHON_SUFFIX="]"
SPACESHIP_PYTHON_SYMBOL="🐍 "
SPACESHIP_PYTHON_COLOR="yellow"

# Rust
SPACESHIP_RUST_SHOW=true
SPACESHIP_RUST_PREFIX="["
SPACESHIP_RUST_SUFFIX="]"
SPACESHIP_RUST_SYMBOL="🦀 "
SPACESHIP_RUST_COLOR="red"

# Go
SPACESHIP_GOLANG_SHOW=true
SPACESHIP_GOLANG_PREFIX="["
SPACESHIP_GOLANG_SUFFIX="]"
SPACESHIP_GOLANG_SYMBOL="🐹 "
SPACESHIP_GOLANG_COLOR="cyan"

# Docker
SPACESHIP_DOCKER_SHOW=true
SPACESHIP_DOCKER_PREFIX="["
SPACESHIP_DOCKER_SUFFIX="]"
SPACESHIP_DOCKER_SYMBOL="🐳 "
SPACESHIP_DOCKER_COLOR="cyan"

# Java
SPACESHIP_JAVA_SHOW=true
SPACESHIP_JAVA_PREFIX="["
SPACESHIP_JAVA_SUFFIX="]"
SPACESHIP_JAVA_SYMBOL="☕ "
SPACESHIP_JAVA_COLOR="red"

# PHP
SPACESHIP_PHP_SHOW=true
SPACESHIP_PHP_PREFIX="["
SPACESHIP_PHP_SUFFIX="]"
SPACESHIP_PHP_SYMBOL="🐘 "
SPACESHIP_PHP_COLOR="blue"

# Swift
SPACESHIP_SWIFT_SHOW=true
SPACESHIP_SWIFT_PREFIX="["
SPACESHIP_SWIFT_SUFFIX="]"
SPACESHIP_SWIFT_SYMBOL="🦅 "
SPACESHIP_SWIFT_COLOR="yellow"

# Kotlin
SPACESHIP_KOTLIN_SHOW=true
SPACESHIP_KOTLIN_PREFIX="["
SPACESHIP_KOTLIN_SUFFIX="]"
SPACESHIP_KOTLIN_SYMBOL="🎯 "
SPACESHIP_KOTLIN_COLOR="magenta"

# Elixir
SPACESHIP_ELIXIR_SHOW=true
SPACESHIP_ELIXIR_PREFIX="["
SPACESHIP_ELIXIR_SUFFIX="]"
SPACESHIP_ELIXIR_SYMBOL="💧 "
SPACESHIP_ELIXIR_COLOR="magenta"

# Lua
SPACESHIP_LUA_SHOW=true
SPACESHIP_LUA_PREFIX="["
SPACESHIP_LUA_SUFFIX="]"
SPACESHIP_LUA_SYMBOL="🌙 "
SPACESHIP_LUA_COLOR="blue"

# Terraform
SPACESHIP_TERRAFORM_SHOW=true
SPACESHIP_TERRAFORM_PREFIX="["
SPACESHIP_TERRAFORM_SUFFIX="]"
SPACESHIP_TERRAFORM_SYMBOL="🏗️  "
SPACESHIP_TERRAFORM_COLOR="magenta"

# Zig
SPACESHIP_ZIG_SHOW=true
SPACESHIP_ZIG_PREFIX="["
SPACESHIP_ZIG_SUFFIX="]"
SPACESHIP_ZIG_SYMBOL="⚡ "
SPACESHIP_ZIG_COLOR="yellow"

# Haskell
SPACESHIP_HASKELL_SHOW=true
SPACESHIP_HASKELL_PREFIX="["
SPACESHIP_HASKELL_SUFFIX="]"
SPACESHIP_HASKELL_SYMBOL="λ "
SPACESHIP_HASKELL_COLOR="magenta"

# Scala
SPACESHIP_SCALA_SHOW=true
SPACESHIP_SCALA_PREFIX="["
SPACESHIP_SCALA_SUFFIX="]"
SPACESHIP_SCALA_SYMBOL="🔴 "
SPACESHIP_SCALA_COLOR="red"

# Execution time
SPACESHIP_EXEC_TIME_SHOW=true
SPACESHIP_EXEC_TIME_PREFIX="took "
SPACESHIP_EXEC_TIME_SUFFIX=" "
SPACESHIP_EXEC_TIME_COLOR="yellow"
SPACESHIP_EXEC_TIME_ELAPSED=2

# Jobs
SPACESHIP_JOBS_SHOW=true
SPACESHIP_JOBS_PREFIX=""
SPACESHIP_JOBS_SUFFIX=" "
SPACESHIP_JOBS_SYMBOL="✦"
SPACESHIP_JOBS_COLOR="blue"
SPACESHIP_JOBS_AMOUNT_PREFIX=""
SPACESHIP_JOBS_AMOUNT_SUFFIX=""
SPACESHIP_JOBS_AMOUNT_THRESHOLD=1

# Exit code
SPACESHIP_EXIT_CODE_SHOW=false
SPACESHIP_EXIT_CODE_PREFIX="("
SPACESHIP_EXIT_CODE_SUFFIX=") "
SPACESHIP_EXIT_CODE_SYMBOL="✘ "
SPACESHIP_EXIT_CODE_COLOR="red"

# Order of prompt sections
SPACESHIP_PROMPT_ORDER=(
  time          # Time stamps section
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git           # Git section (git_branch + git_status)
  bun           # Bun section
  node          # Node.js section
  python        # Python section
  ruby          # Ruby section
  rust          # Rust section
  golang        # Go section
  java          # Java section
  kotlin        # Kotlin section
  swift         # Swift section
  php           # PHP section
  elixir        # Elixir section
  haskell       # Haskell section
  scala         # Scala section
  lua           # Lua section
  zig           # Zig section
  docker        # Docker section
  terraform     # Terraform section
  aws           # AWS section
  exec_time     # Execution time
  line_sep      # Line break
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
)

# Order of right prompt sections
SPACESHIP_RPROMPT_ORDER=(
  # Empty by default
)
